name: zenoh_dart
description: "Dart bindings for the Zenoh pub/sub/query protocol via FFI."
version: 0.20.0
repository: https://github.com/bluecorn/zenoh_dart
issue_tracker: https://github.com/bluecorn/zenoh_dart/issues

topics:
  - zenoh
  - ffi
  - pubsub
  - networking
  - iot

platforms:
  android:
  linux:

environment:
  sdk: ^3.12.2

dependencies:
  args: ^2.6.0
  code_assets: ^1.0.0
  ffi: ^2.1.3
  hooks: ^1.0.0

dev_dependencies:
  ffigen: ^20.1.1
  lints: ^5.1.0
  test: ^1.25.0
